on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: ./build.sh --target build --configuration Release
      - run: ./build.sh --target pack --configuration Release --no-build
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            artifacts/pkg/*.nupkg
            artifacts/pkg/*.snupkg
      - uses: actions/upload-artifact@v3
        with:
          name: libraries
          with: |
            artifacts/lib/*.zip
